subprojects {
    apply plugin: 'java-library'

    group = 'org.msuo'
    version = '0.0.3'

    repositories {
        mavenCentral()
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter:5.14.2'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.14.2'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = 11
    }
}
